package com.myspace.prjseguros;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Bien implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "BIEN_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "BIEN_ID_GENERATOR", sequenceName = "BIEN_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Nombre del bien")
	private java.lang.String nombre;

	@org.kie.api.definition.type.Label("Valor del bien")
	private java.lang.Float valor;

	@org.kie.api.definition.type.Label(value = "Tipo de bien")
	private java.lang.String tipo;

	public Bien() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.Float getValor() {
		return this.valor;
	}

	public void setValor(java.lang.Float valor) {
		this.valor = valor;
	}

	public java.lang.String getTipo() {
		return this.tipo;
	}

	public void setTipo(java.lang.String tipo) {
		this.tipo = tipo;
	}

	public Bien(java.lang.Long id, java.lang.String nombre,
			java.lang.Float valor, java.lang.String tipo) {
		this.id = id;
		this.nombre = nombre;
		this.valor = valor;
		this.tipo = tipo;
	}

}